package ru.ksoft.springaiyandexgpt.constants;

public enum CompletionResponseStatus {
    ALTERNATIVE_STATUS_UNSPECIFIED,
    ALTERNATIVE_STATUS_PARTIAL,
    ALTERNATIVE_STATUS_TRUNCATED_FINAL,
    ALTERNATIVE_STATUS_FINAL,
    ALTERNATIVE_STATUS_CONTENT_FILTER,
    ALTERNATIVE_STATUS_TOOL_CALLS;
}
